swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /search:
    get:
      operationId: "Runner.search"
      tags:
        - "Search"
      summary: "Does a search by the given term"
      description: "Does a search by the given term"
      parameters:
        - name: term
          in: query
          type: string
          description: Term for search
          required: true
      responses:
        200:
          description: "The code of the search"
          schema:
            properties:
              searchId:
                type: string
  /results:
    get:
      operationId: "Runner.getResults"
      tags:
        - "results"
      summary: "Gets the results from a given Id"
      description: "Gets the results from a given Id"
      parameters:
        - name: searchId
          in: query
          type: string
          description: Id of the search
          required: true
      responses:
        200:
          description: "The Search Results"
          schema:
            properties:
              postList:
                type: array
  /mostSearched:
    get:
      operationId: "Runner.getMostSearched"
      tags:
        - "mostSearched"
      summary: "Gets the most searched terms"
      description: "Gets the most searched terms"
      responses:
        200:
          description: "The list"
          schema:
            properties:
              termList:
                type: array
  /latestSearchs:
    get:
      operationId: "Runner.getLatestSearchs"
      tags:
        - "latestSearchs"
      summary: "Gets the lastest searchs"
      description: "Gets the lastest searchs"
      responses:
        200:
          description: "The list"
          schema:
            properties:
              termList:
                type: array